### ISSUE TITLE
Invalid tests for `strcmp`

### ISSUE THREAD

**Issue by Sigmanificient** [QuentindiMeo/tek-pool-challenge#1]
Hi, i noticed that the tests for `strcmp` are invalid. Indeed, your tests are waiting for a return value clamped between `-1` and `0` which is not an hard requirement of the original function. The man page precise the following for the return value:

> *strcmp() returns an integer indicating the result of the comparison, as follows:
> •  0, if the s1 and s2 are equal;
> •  a negative value if s1 is less than s2;
> •  a positive value if s1 is greater than s2.*

Moreover, it is annotated at the end that common implementations often use the difference between the 2 latest characters:

> *In  glibc,  as  in most other implementations, the return value is the arithmetic result of subtracting the
> last compared byte in s2 from the last compared byte in s1.  (If the two characters are equal, this differ‐
> ence is 0.)*

This is also not a requirement, and the return value should not be interpreted, only its sign. Subsequent tests should consider using a boolean expression, depending on the inputs to comply with the broader standard.

Null inputs are not not part of the standard, and are by definition undefined behavior, so tests on them are also invalids.

Thanks

**Comment by QuentindiMeo** [comment]
Hi Yohann, thank you for reporting!
Indeed, as this project was sparked as a result of a one-day-one-idea scope, I know some of the tests are incomplete as the project is overall.
I'll be looking into this malfunction this evening.

**Comment by QuentindiMeo** [comment]
Okay, this is gonna sound like the most zealous comment you've ever heard, but the subject explicitly states "Reproduce the behavior of the `strcmp` function." Considering that `strcmp` empirically does return [-1 | 0 | 1], we're going with this.
Your note remains interesting because, if `strcmp` doesn't, `strncmp` DOES return the aforementioned substraction as a result, I will therefore be adjusting the expected results for _that_ function.

For about the three NULL tests, you are totally right; I'm removing them.

**Comment by Sigmanificient** [comment]
As stated above, both `strcmp` and `strncmp` functions do not have constraint on their respective return values, only on the integer sign. Here is quoted from C standard:

> ***7.21.4.2 The strcmp function***
>
> ***Synopsis***
> *`#include <string.h>`
> `int strcmp(const char *s1, const char *s2);`*
>
> ***Description**
> The strcmp function compares the string pointed to by s1 to the string pointed to by s2.*
>
> ***Returns**
> The strcmp function returns an integer greater than, equal to, or less than zero, accordingly as the string pointed to by s1 is greater than, equal to, or less than the string point by s2.*

[...]

> ***7.21.4.4 The strncmp function***
>
> ***Synopsis***
> `#include <string.h>`
> `int strncmp(const char *s1, const char *s2, size_t n);`
>
> ***Description***
> *The strncmp function compares not more than n characters (characters that follow a null character are not compared) from the array pointed to by s1 to the array pointed to by s2.*
>
> ***Returns**
> The strncmp function returns an integer greater than, equal to, or less than zero, accordingly as the possibly null-terminated array pointed to by s1 is greater than, equal to, or less than the possibly null-terminated array pointed to by s2.*

**Comment by QuentindiMeo** [comment]
What you are saying is completely true. And the EPITECH subject might have changed from the time I passed it. However, in an attempt to "reproduce the behavior of the `strcmp` function", returning [-1 |0 | 1] remains closest to what is found in reality---and therefore fits best the purpose of this challenge. You can call it a bias, but don't shoot the messenger!

**Comment by Sigmanificient** [comment]
Epitech inforce the usage of gcc, and the compiler libc, aka glibc source for both `strcmp` and `strncmp` do indeed compute the character difference to comply C standard and POSIX.
See the sources for [strcmp](https://sourceware.org/git/?p=glibc.git;a=blob;f=string/strcmp.c;h=2bca399f5205511074e530f19ff3dc3e7d88a1a9;hb=refs/heads/master#l112) and [strncmp](https://sourceware.org/git/?p=glibc.git;a=blob;f=string/strncmp.c;h=67cc97542a6b1d359c73b4da1156140360a17127;hb=refs/heads/master#l125)

**Comment by QuentindiMeo** [comment]
I do not disagree with the examples or principles you provide. And indeed, EPITECH enforces the use of gcc.
However: using a gcc 12.2 compiler, `strcmp` returns 0, -1 or 1. Are you able to provide me with an example of a standard gcc `strcmp` implementation that returns another numeric value?
Until then, the expected return values in the related exercises will remain the same.

**Comment by Sigmanificient** [comment]
The sources i provided to you return the numerical difference.
Many this other point will convince you more, the official T.A. test does checks only the sign, and thus the difference implementation is accepted:

![image](https://github.com/QuentindiMeo/tek-pool-challenge/assets/53050011/705c2c8a-d443-47b0-8a9c-de9f2c7013d6)
You can see the code i used for the commit were the test passed

**Comment by QuentindiMeo** [comment]
Now _that_ looks like a motive for a change. On it.
